/*  Copyright(c) 2009-2011 Shenzhen TP-LINK Technologies Co.Ltd.
 *
 * file		oid_path.js
 * brief	Define object full path for web.	
 * details	
 *
 * author	Wu Zhiqin
 * version	1.0.0
 * date		16Jun20

 *
 * history 	\arg	
 */

/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*! file oid_path.js 
 * brief Automatically generated header file oid_path.js
 */


/*
 * brief Define object full path for web.
 */
var oid_str = [
/*   0 */ undefined,
/*   1 */ "InternetGatewayDevice.",
/*   2 */ "InternetGatewayDevice.WANDevice.{i}.",
/*   3 */ "InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig.",
/*   4 */ "InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig.Connection.{i}.",
/*   5 */ "InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.",
/*   6 */ "InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats.",
/*   7 */ "InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.",
/*   8 */ "InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.",
/*   9 */ "InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.",
/*  10 */ "InternetGatewayDevice.ModelName.",
/*  11 */ "InternetGatewayDevice.X_TPLINK_NetCfg.",
/*  12 */ "InternetGatewayDevice.X_TPLINK_UserCfg.",
/*  13 */ "InternetGatewayDevice.X_TPLINK_AppCfg.",
/*  14 */ "InternetGatewayDevice.X_TPLINK_AppCfg.HttpCfg.",
/*  15 */ "InternetGatewayDevice.LANDevice.{i}.",
/*  16 */ "InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.",
/*  17 */ "InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.",
/*  18 */ "InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPStaticAddress.{i}.",
/*  19 */ "InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.",
/*  20 */ "InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.DHCPOption.{i}.",
/*  21 */ "InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.",
/*  22 */ "InternetGatewayDevice.LANDevice.{i}.Hosts.",
/*  23 */ "InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}.",
/*  24 */ "InternetGatewayDevice.X_TPLINK_Switch.",
/*  25 */ "InternetGatewayDevice.X_TPLINK_Switch.BridgeRstp.",
/*  26 */ "InternetGatewayDevice.X_TPLINK_Switch.BridgeRstp.BridgeRstpRTInfo.",
/*  27 */ "InternetGatewayDevice.X_TPLINK_Switch.IGMP.",
/*  28 */ "InternetGatewayDevice.X_TPLINK_Switch.IGMP.IgmpRTInfo.",
/*  29 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.",
/*  30 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.StormSuppress.",
/*  31 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.RateLimit.",
/*  32 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.PortRstp.",
/*  33 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.PortRstp.PortRstpRTInfo.",
/*  34 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.MacFilter.{i}.",
/*  35 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.StaticMac.{i}.",
/*  36 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.SwitchRtStats.",
/*  37 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.SwitchTimeStats.",
/*  38 */ "InternetGatewayDevice.X_TPLINK_Switch.SwitchPort.{i}.SwitchRuntimeData.",
/*  39 */ "InternetGatewayDevice.X_TPLINK_Pon.{i}.",
/*  40 */ "InternetGatewayDevice.X_TPLINK_Pon.{i}.OpticalStats.",
/*  41 */ "InternetGatewayDevice.X_TPLINK_Pon.{i}.PonRegInfo.",
/*  42 */ "InternetGatewayDevice.X_TPLINK_Pon.{i}.OmciRtStats.",
/*  43 */ "InternetGatewayDevice.X_TPLINK_Pon.{i}.UniStats.",
/*  44 */ "InternetGatewayDevice.X_TPLINK_Pon.{i}.PonRtStats.",
/*  45 */ "InternetGatewayDevice.X_TPLINK_Pon.{i}.PonTimeStats.",
/*  46 */ "InternetGatewayDevice.X_TPLINK_PonCfg.",
/*  47 */ "InternetGatewayDevice.X_TPLINK_PonCfg.PonAuthCtc.",
/*  48 */ "InternetGatewayDevice.X_TPLINK_PonCfg.EponAuthMac.",
/*  49 */ "InternetGatewayDevice.X_TPLINK_PonCfg.EponOnuSn.{i}.",
/*  50 */ "InternetGatewayDevice.X_TPLINK_PonCfg.EponChipsetID.{i}.",
/*  51 */ "InternetGatewayDevice.X_TPLINK_PonCfg.EponCapabilities.{i}.",
/*  52 */ "InternetGatewayDevice.X_TPLINK_PonCfg.GponAuthSn.",
/*  53 */ "InternetGatewayDevice.X_TPLINK_PonCfg.GponOnuSn.{i}.",
/*  54 */ "InternetGatewayDevice.X_TPLINK_PonCfg.GponAuthPwd.",
/*  55 */ "InternetGatewayDevice.X_TPLINK_PonCfg.GponTcont.",
/*  56 */ "InternetGatewayDevice.X_TPLINK_PonCfg.GponDebug.",
/*  57 */ "InternetGatewayDevice.X_TPLINK_statsParameter.",
/*  58 */ "InternetGatewayDevice.X_TPLINK_oamStats.",
/*  59 */ "InternetGatewayDevice.X_TPLINK_mpcpStats.",
/*  60 */ "InternetGatewayDevice.Services.",
/*  61 */ "InternetGatewayDevice.Services.VoiceService.{i}.",
/*  62 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_CTC_GlobalParameterConfig.",
/*  63 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_CTC_SIPParameterConfig.",
/*  64 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_CTC_FaxModemConfig.",
/*  65 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_CTC_POTSStatus.",
/*  66 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_CTC_IADOperation.",
/*  67 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_CTC_SIPDigitMap.",
/*  68 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_VoiceProcessSts.",
/*  69 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_VoiceProcess.",
/*  70 */ "InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.",
/*  71 */ "InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.SIP.",
/*  72 */ "InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.MGCP.",
/*  73 */ "InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.Codecs.{i}.",
/*  74 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.",
/*  75 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.ServiceProviderInfo.",
/*  76 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP.",
/*  77 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP.EventSubscribe.{i}.",
/*  78 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.MGCP.",
/*  79 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP.",
/*  80 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.FaxT38.",
/*  81 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.X_TPLINK_UsbVoiceMail.",
/*  82 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.X_TPLINK_MultiIsp.{i}.",
/*  83 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.X_TPLINK_MultiIsp.{i}.Codec.",
/*  84 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.X_TPLINK_MultiIsp.{i}.Codec.List.{i}.",
/*  85 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.",
/*  86 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.SIP.",
/*  87 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_TPLINK_UsbVoiceMail.",
/*  88 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.CallingFeatures.",
/*  89 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.VoiceProcessing.",
/*  90 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.",
/*  91 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.List.{i}.",
/*  92 */ "InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Stats.",
/*  93 */ "InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}.",
/*  94 */ "InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}.Tests.",
/*  95 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_MultiIspDialPlan.",
/*  96 */ "InternetGatewayDevice.Services.VoiceService.{i}.X_TPLINK_PSTN.{i}.",
/*  97 */ "InternetGatewayDevice.X_TPLINK_CallFireWallCfg.",
/*  98 */ "InternetGatewayDevice.X_TPLINK_SpeedDialCfg.",
/*  99 */ "InternetGatewayDevice.X_TPLINK_MultiIspDialPlan.",
/* 100 */ "InternetGatewayDevice.X_TPLINK_MultiIspDialPlan.List.{i}.",
/* 101 */ "InternetGatewayDevice.X_TPLINK_CallLogCfg.",
/* 102 */ "InternetGatewayDevice.X_TPLINK_PonVlanScan.",
/* 103 */ "InternetGatewayDevice.X_TPLINK_PonVlanScan.VlanScanResult.{i}.",
/* 104 */ "InternetGatewayDevice.X_TPLINK_PonMulticastVlan.",
/* 105 */ "InternetGatewayDevice.X_TPLINK_EponVlanMode.",
/* 106 */ "InternetGatewayDevice.X_TPLINK_GponFwRule.",
/* 107 */ "InternetGatewayDevice.X_TPLINK_GponFwRule.FwRuleEntryLocal.{i}.",
/* 108 */ "InternetGatewayDevice.X_TPLINK_GponFwRule.FwRuleEntryRemote.{i}.",
/* 109 */ "InternetGatewayDevice.X_TPLINK_GponIotCfg.",
/* 110 */ "InternetGatewayDevice.X_TPLINK_GponIotCfg.IotCfgList.{i}.",
/* 111 */ "InternetGatewayDevice.X_TPLINK_GponIotCfg.IotCfgImport.",
/* 112 */ "InternetGatewayDevice.X_TPLINK_GponOmci.",
/* 113 */ "InternetGatewayDevice.X_TPLINK_GponOmci.OmciMe.{i}.",
/* 114 */ "InternetGatewayDevice.X_TPLINK_GponOmci.OmciMe.{i}.MeAttr.{i}.",
/* 115 */ "InternetGatewayDevice.X_TPLINK_GponOmci.OmciMeRT.{i}.",
/* 116 */ "InternetGatewayDevice.X_TPLINK_GponOmci.OmciMeRT.{i}.MeAttrRT.{i}.",
/* 117 */ "InternetGatewayDevice.X_TPLINK_GponOmci.MeInst.{i}.",
/* 118 */ "InternetGatewayDevice.X_TPLINK_GponOmci.MeInst.{i}.MeIot.{i}.",
/* 119 */ "InternetGatewayDevice.X_TPLINK_EponIotCfg.",
/* 120 */ "InternetGatewayDevice.X_BDCOM_Epon.",
/* 121 */ "InternetGatewayDevice.X_BDCOM_Epon.X_BDCOMWanVlan."
];
